### ISSUE TITLE
Implement tableschema-spss Storage plugin for tableschema

### ISSUE THREAD

**Issue by brew** [frictionlessdata/tableschema-spss-py#2]
Create a tableschema-spss [Storage plugin](https://github.com/frictionlessdata/tableschema-py#storage) for tableschema, using existing Storage plugins as a guide:

https://github.com/frictionlessdata/tableschema-pandas-py
https://github.com/frictionlessdata/tableschema-sql-py
https://github.com/frictionlessdata/tableschema-bigquery-py

Implement the table schema Storage interface for spss .sav files with tests:

- [x] create buckets from descriptors
- [x] write data to bucket
- [x] describe bucket
- [x] delete bucket
- [x] read bucket
- [x] iter bucket

**Comment by brew** [comment]
@pwalsh This is now done, and ready for review (on master).

**Comment by pwalsh** [comment]
@brew 

I've reviewed. Nice work. Can we get this on pypi please.

**Comment by brew** [comment]
@pwalsh Tagged at version 0.1.0 and release on pypi. The `make release` and travis deploy tools are sweet!
